//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaRecycler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Scraper : global::System.Configuration.ApplicationSettingsBase {
        
        private static Scraper defaultInstance = ((Scraper)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Scraper())));
        
        public static Scraper Default {
            get {
                return defaultInstance;
            }
        }
    }
}
